@echo off
echo Pulling latest changes...
git pull origin master --rebase

echo Adding all changes...
git add .

echo Committing changes...
git commit -m "Updated website content"

echo Pushing to GitHub...
git push origin master

echo ✅ Update Complete! Press any key to close...
pause >nul
